version: '3.8'
services:
  web:
    build: .
    environment:
      USERNAME: ${USERNAME}
      PASSWORD: ${PASSWORD}
    ports:
    - "5000:5000"
    volumes:
    - .:/opt
    links:
    - mongo

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${PASSWORD}
    ports:
      - "8000:27017"
    volumes:
      - mongo-data:/data/db
      - mongo-configdb:/data/configdb
volumes:
  mongo-data:
  mongo-configdb: